### ISSUE TITLE
Fails to install when following a symlinked path.

### ISSUE THREAD

**Issue by olsonbg** [vanderbilt-redcap/flight-tracker#4]
When the `modules` directory in redcap is a symlinked path the install will fail because `__DIR__` resolves the symlink path. 

[https://stackoverflow.com/questions/3221771/how-do-you-get-php-symlinks-and-file-to-work-together-nicely](https://stackoverflow.com/questions/3221771/how-do-you-get-php-symlinks-and-file-to-work-together-nicely).

It looks like most `__DIR__ .` can be removed with either including a '.' or removing a leading '/' from the paths.

**Comment by scottjpearson** [comment]
Brian, I just saw this, and I'll investigate. I'm not sure we'll be able to address symlinks, but I'll investigate.

@mmcev106 I've never encountered this setup before, but it'd affect almost every External Module, no? I'd be curious for you to weigh in before I take action. Years ago, I believe I had trouble with using '.' instead of __DIR__ or dirname(__FILE__), but I don't remember details. If you don't recall either, I can dig deeper.

**Comment by mmcev106** [comment]
I don't believe we are able to officially support symlinking the `modules` directory, and would expect it to cause problems with certain modules.  I would recommend using the `Alternate module directories` feature instead of a symlink to inform REDCap on where to look for modules.  It can be found under `Control Center -> Modules/Services Configuration`.

**Comment by scottjpearson** [comment]
Thanks for your reply @mmcev106. I'm going to pass on action here, then. Thanks for your interest @olsonbg.

**Comment by olsonbg** [comment]
Thanks for looking into this @scottjpearson; I'll try the suggestion from @mmcev106.
